spring.application.name=demo-keycloak
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/demo-db
spring.datasource.username=${DB_USERNAME:demo-user}
spring.datasource.password=${DB_PASSWORD:demo-pass}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions = true

